### ISSUE TITLE
create banker contract function which handles how the money are being split

### ISSUE THREAD

**Issue by ghost** [jparicka/blockchain-notary#11]

**Comment by ghost** [comment]
remember that -

Well, there is a cost associated to this service and it's compromised of 2 things: 
1 - 0.01 ETH is the cost for submitting the contract to the Blockchain (it's the standard network fee) 
2 - 0.99 ETH is for Jan Paricka because he is a very good developer, we all love him and we want him to have tons of money

**Comment by janfilips** [comment]
done
