### ISSUE TITLE
"read more" button on the right seems a little bit off

### ISSUE THREAD

**Issue by janfilips** [jparicka/blockchain-notary#21]
<img width="1004" alt="screen shot 2018-05-12 at 10 58 49" src="https://user-images.githubusercontent.com/870699/39955677-8eec669c-55d3-11e8-8865-178f2f2aeb65.png">

**Comment by jparicka** [comment]
also maybe make it a tiny little bit bigger?

**Comment by janfilips** [comment]
Apparently the one on the right on the picture has a bigger button next to it.  I did not see it.

**Comment by janfilips** [comment]
fixed
