### ISSUE TITLE
missing archors maybe?

### ISSUE THREAD

**Issue by janfilips** [jparicka/blockchain-notary#22]
Seems like this "Notarise" button doesn't do much - 

<img width="425" alt="screen shot 2018-05-12 at 14 19 17" src="https://user-images.githubusercontent.com/870699/39957219-93f5ef48-55ef-11e8-9f31-30772284ff2d.png">

I think this button should point to the #notarise anchor, just above the drop zone...

**Comment by ghost** [comment]
I removed anchor accidentaly when imported Dropzone maybe.

**Comment by ghost** [comment]
I will fix it

**Comment by janfilips** [comment]
actually this is a JS problem....

so igor would be the guy to talk to 💯
