### ISSUE TITLE
space between text and the tx link

### ISSUE THREAD

**Issue by janfilips** [jparicka/blockchain-notary#38]

**Comment by ghost** [comment]
Need example. Issue name is not quite descriptive @jparicka

**Comment by janfilips** [comment]
I meant the spacing between text -

<img width="729" alt="screen shot 2018-06-09 at 15 08 51" src="https://user-images.githubusercontent.com/870699/41191945-12ea9f02-6bf7-11e8-9cb0-6e44b8a82f69.png">
