### ISSUE TITLE
redirect for an existing verified docu(s) is a must!

### ISSUE THREAD

**Issue by janfilips** [jparicka/blockchain-notary#40]

**Comment by janfilips** [comment]
can we have this on a popup saying something like -

This document has been notarised on the xx.yy.yyyy.

You have the original document.

The document proof can be found here <link>

**Comment by janfilips** [comment]
button instead of OK saying "See the Proof"

**Comment by ghost** [comment]
Removed "The document proof can be found here" due to redundancy

**Comment by ghost** [comment]
Done
